-- CreateTable
CREATE TABLE "Country" (
    "code" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "continent" TEXT NOT NULL,
    "aliases" TEXT[] DEFAULT ARRAY[]::TEXT[],

    CONSTRAINT "Country_pkey" PRIMARY KEY ("code")
);

-- CreateIndex
CREATE INDEX "Country_continent_idx" ON "Country"("continent");

-- Data: every ISO 3166-1 country (plus Kosovo, XK, which hosts can report), with
-- UN M49-based continents; the Americas are split into North (with Central
-- America and the Caribbean) and South.
INSERT INTO "Country" ("code", "name", "continent", "aliases") VALUES
('AF', 'Afghanistan', 'Asia', ARRAY[]::TEXT[]),
('AX', 'Åland Islands', 'Europe', ARRAY[]::TEXT[]),
('AL', 'Albania', 'Europe', ARRAY[]::TEXT[]),
('DZ', 'Algeria', 'Africa', ARRAY[]::TEXT[]),
('AS', 'American Samoa', 'Oceania', ARRAY[]::TEXT[]),
('AD', 'Andorra', 'Europe', ARRAY[]::TEXT[]),
('AO', 'Angola', 'Africa', ARRAY[]::TEXT[]),
('AI', 'Anguilla', 'North America', ARRAY[]::TEXT[]),
('AQ', 'Antarctica', 'Antarctica', ARRAY[]::TEXT[]),
('AG', 'Antigua & Barbuda', 'North America', ARRAY[]::TEXT[]),
('AR', 'Argentina', 'South America', ARRAY[]::TEXT[]),
('AM', 'Armenia', 'Asia', ARRAY[]::TEXT[]),
('AW', 'Aruba', 'North America', ARRAY[]::TEXT[]),
('AU', 'Australia', 'Oceania', ARRAY[]::TEXT[]),
('AT', 'Austria', 'Europe', ARRAY[]::TEXT[]),
('AZ', 'Azerbaijan', 'Asia', ARRAY[]::TEXT[]),
('BS', 'Bahamas', 'North America', ARRAY[]::TEXT[]),
('BH', 'Bahrain', 'Asia', ARRAY[]::TEXT[]),
('BD', 'Bangladesh', 'Asia', ARRAY[]::TEXT[]),
('BB', 'Barbados', 'North America', ARRAY[]::TEXT[]),
('BY', 'Belarus', 'Europe', ARRAY[]::TEXT[]),
('BE', 'Belgium', 'Europe', ARRAY[]::TEXT[]),
('BZ', 'Belize', 'North America', ARRAY[]::TEXT[]),
('BJ', 'Benin', 'Africa', ARRAY[]::TEXT[]),
('BM', 'Bermuda', 'North America', ARRAY[]::TEXT[]),
('BT', 'Bhutan', 'Asia', ARRAY[]::TEXT[]),
('BO', 'Bolivia', 'South America', ARRAY['Bolivia']),
('BA', 'Bosnia & Herzegovina', 'Europe', ARRAY[]::TEXT[]),
('BW', 'Botswana', 'Africa', ARRAY[]::TEXT[]),
('BV', 'Bouvet Island', 'South America', ARRAY[]::TEXT[]),
('BR', 'Brazil', 'South America', ARRAY[]::TEXT[]),
('IO', 'British Indian Ocean Territory', 'Africa', ARRAY[]::TEXT[]),
('VG', 'British Virgin Islands', 'North America', ARRAY[]::TEXT[]),
('BN', 'Brunei', 'Asia', ARRAY[]::TEXT[]),
('BG', 'Bulgaria', 'Europe', ARRAY[]::TEXT[]),
('BF', 'Burkina Faso', 'Africa', ARRAY[]::TEXT[]),
('BI', 'Burundi', 'Africa', ARRAY[]::TEXT[]),
('KH', 'Cambodia', 'Asia', ARRAY[]::TEXT[]),
('CM', 'Cameroon', 'Africa', ARRAY[]::TEXT[]),
('CA', 'Canada', 'North America', ARRAY[]::TEXT[]),
('CV', 'Cape Verde', 'Africa', ARRAY['Cabo Verde']),
('BQ', 'Caribbean Netherlands', 'North America', ARRAY[]::TEXT[]),
('KY', 'Cayman Islands', 'North America', ARRAY[]::TEXT[]),
('CF', 'Central African Republic', 'Africa', ARRAY[]::TEXT[]),
('TD', 'Chad', 'Africa', ARRAY[]::TEXT[]),
('CL', 'Chile', 'South America', ARRAY[]::TEXT[]),
('CN', 'China', 'Asia', ARRAY[]::TEXT[]),
('CX', 'Christmas Island', 'Oceania', ARRAY[]::TEXT[]),
('CC', 'Cocos (Keeling) Islands', 'Oceania', ARRAY[]::TEXT[]),
('CO', 'Colombia', 'South America', ARRAY[]::TEXT[]),
('KM', 'Comoros', 'Africa', ARRAY[]::TEXT[]),
('CK', 'Cook Islands', 'Oceania', ARRAY[]::TEXT[]),
('CR', 'Costa Rica', 'North America', ARRAY[]::TEXT[]),
('CI', 'Côte d’Ivoire', 'Africa', ARRAY['Ivory Coast']),
('HR', 'Croatia', 'Europe', ARRAY[]::TEXT[]),
('CU', 'Cuba', 'North America', ARRAY[]::TEXT[]),
('CW', 'Curaçao', 'North America', ARRAY[]::TEXT[]),
('CY', 'Cyprus', 'Europe', ARRAY[]::TEXT[]),
('CZ', 'Czechia', 'Europe', ARRAY['Czech Republic']),
('DK', 'Denmark', 'Europe', ARRAY[]::TEXT[]),
('DJ', 'Djibouti', 'Africa', ARRAY[]::TEXT[]),
('DM', 'Dominica', 'North America', ARRAY[]::TEXT[]),
('DO', 'Dominican Republic', 'North America', ARRAY[]::TEXT[]),
('CD', 'DR Congo', 'Africa', ARRAY['Congo', 'Zaire', 'DRC']),
('EC', 'Ecuador', 'South America', ARRAY[]::TEXT[]),
('EG', 'Egypt', 'Africa', ARRAY[]::TEXT[]),
('SV', 'El Salvador', 'North America', ARRAY[]::TEXT[]),
('GQ', 'Equatorial Guinea', 'Africa', ARRAY[]::TEXT[]),
('ER', 'Eritrea', 'Africa', ARRAY[]::TEXT[]),
('EE', 'Estonia', 'Europe', ARRAY[]::TEXT[]),
('SZ', 'Eswatini', 'Africa', ARRAY['Swaziland']),
('ET', 'Ethiopia', 'Africa', ARRAY[]::TEXT[]),
('FK', 'Falkland Islands', 'South America', ARRAY[]::TEXT[]),
('FO', 'Faroe Islands', 'Europe', ARRAY[]::TEXT[]),
('FJ', 'Fiji', 'Oceania', ARRAY[]::TEXT[]),
('FI', 'Finland', 'Europe', ARRAY[]::TEXT[]),
('FR', 'France', 'Europe', ARRAY[]::TEXT[]),
('GF', 'French Guiana', 'South America', ARRAY[]::TEXT[]),
('PF', 'French Polynesia', 'Oceania', ARRAY[]::TEXT[]),
('TF', 'French Southern Territories', 'Africa', ARRAY[]::TEXT[]),
('GA', 'Gabon', 'Africa', ARRAY[]::TEXT[]),
('GM', 'Gambia', 'Africa', ARRAY[]::TEXT[]),
('GE', 'Georgia', 'Asia', ARRAY[]::TEXT[]),
('DE', 'Germany', 'Europe', ARRAY[]::TEXT[]),
('GH', 'Ghana', 'Africa', ARRAY[]::TEXT[]),
('GI', 'Gibraltar', 'Europe', ARRAY[]::TEXT[]),
('GR', 'Greece', 'Europe', ARRAY[]::TEXT[]),
('GL', 'Greenland', 'North America', ARRAY[]::TEXT[]),
('GD', 'Grenada', 'North America', ARRAY[]::TEXT[]),
('GP', 'Guadeloupe', 'North America', ARRAY[]::TEXT[]),
('GU', 'Guam', 'Oceania', ARRAY[]::TEXT[]),
('GT', 'Guatemala', 'North America', ARRAY[]::TEXT[]),
('GG', 'Guernsey', 'Europe', ARRAY[]::TEXT[]),
('GN', 'Guinea', 'Africa', ARRAY[]::TEXT[]),
('GW', 'Guinea-Bissau', 'Africa', ARRAY[]::TEXT[]),
('GY', 'Guyana', 'South America', ARRAY[]::TEXT[]),
('HT', 'Haiti', 'North America', ARRAY[]::TEXT[]),
('HM', 'Heard & McDonald Islands', 'Oceania', ARRAY[]::TEXT[]),
('HN', 'Honduras', 'North America', ARRAY[]::TEXT[]),
('HK', 'Hong Kong', 'Asia', ARRAY['Hong Kong SAR']),
('HU', 'Hungary', 'Europe', ARRAY[]::TEXT[]),
('IS', 'Iceland', 'Europe', ARRAY[]::TEXT[]),
('IN', 'India', 'Asia', ARRAY[]::TEXT[]),
('ID', 'Indonesia', 'Asia', ARRAY[]::TEXT[]),
('IR', 'Iran', 'Asia', ARRAY['Persia']),
('IQ', 'Iraq', 'Asia', ARRAY[]::TEXT[]),
('IE', 'Ireland', 'Europe', ARRAY[]::TEXT[]),
('IM', 'Isle of Man', 'Europe', ARRAY[]::TEXT[]),
('IL', 'Israel', 'Asia', ARRAY[]::TEXT[]),
('IT', 'Italy', 'Europe', ARRAY[]::TEXT[]),
('JM', 'Jamaica', 'North America', ARRAY[]::TEXT[]),
('JP', 'Japan', 'Asia', ARRAY[]::TEXT[]),
('JE', 'Jersey', 'Europe', ARRAY[]::TEXT[]),
('JO', 'Jordan', 'Asia', ARRAY[]::TEXT[]),
('KZ', 'Kazakhstan', 'Asia', ARRAY[]::TEXT[]),
('KE', 'Kenya', 'Africa', ARRAY[]::TEXT[]),
('KI', 'Kiribati', 'Oceania', ARRAY[]::TEXT[]),
('XK', 'Kosovo', 'Europe', ARRAY[]::TEXT[]),
('KW', 'Kuwait', 'Asia', ARRAY[]::TEXT[]),
('KG', 'Kyrgyzstan', 'Asia', ARRAY[]::TEXT[]),
('LA', 'Laos', 'Asia', ARRAY['Laos']),
('LV', 'Latvia', 'Europe', ARRAY[]::TEXT[]),
('LB', 'Lebanon', 'Asia', ARRAY[]::TEXT[]),
('LS', 'Lesotho', 'Africa', ARRAY[]::TEXT[]),
('LR', 'Liberia', 'Africa', ARRAY[]::TEXT[]),
('LY', 'Libya', 'Africa', ARRAY[]::TEXT[]),
('LI', 'Liechtenstein', 'Europe', ARRAY[]::TEXT[]),
('LT', 'Lithuania', 'Europe', ARRAY[]::TEXT[]),
('LU', 'Luxembourg', 'Europe', ARRAY[]::TEXT[]),
('MO', 'Macao', 'Asia', ARRAY[]::TEXT[]),
('MG', 'Madagascar', 'Africa', ARRAY[]::TEXT[]),
('MW', 'Malawi', 'Africa', ARRAY[]::TEXT[]),
('MY', 'Malaysia', 'Asia', ARRAY[]::TEXT[]),
('MV', 'Maldives', 'Asia', ARRAY[]::TEXT[]),
('ML', 'Mali', 'Africa', ARRAY[]::TEXT[]),
('MT', 'Malta', 'Europe', ARRAY[]::TEXT[]),
('MH', 'Marshall Islands', 'Oceania', ARRAY[]::TEXT[]),
('MQ', 'Martinique', 'North America', ARRAY[]::TEXT[]),
('MR', 'Mauritania', 'Africa', ARRAY[]::TEXT[]),
('MU', 'Mauritius', 'Africa', ARRAY[]::TEXT[]),
('YT', 'Mayotte', 'Africa', ARRAY[]::TEXT[]),
('MX', 'Mexico', 'North America', ARRAY[]::TEXT[]),
('FM', 'Micronesia', 'Oceania', ARRAY['Micronesia']),
('MD', 'Moldova', 'Europe', ARRAY[]::TEXT[]),
('MC', 'Monaco', 'Europe', ARRAY[]::TEXT[]),
('MN', 'Mongolia', 'Asia', ARRAY[]::TEXT[]),
('ME', 'Montenegro', 'Europe', ARRAY[]::TEXT[]),
('MS', 'Montserrat', 'North America', ARRAY[]::TEXT[]),
('MA', 'Morocco', 'Africa', ARRAY[]::TEXT[]),
('MZ', 'Mozambique', 'Africa', ARRAY[]::TEXT[]),
('MM', 'Myanmar', 'Asia', ARRAY['Burma']),
('NA', 'Namibia', 'Africa', ARRAY[]::TEXT[]),
('NR', 'Nauru', 'Oceania', ARRAY[]::TEXT[]),
('NP', 'Nepal', 'Asia', ARRAY[]::TEXT[]),
('NL', 'Netherlands', 'Europe', ARRAY['Holland']),
('NC', 'New Caledonia', 'Oceania', ARRAY[]::TEXT[]),
('NZ', 'New Zealand', 'Oceania', ARRAY[]::TEXT[]),
('NI', 'Nicaragua', 'North America', ARRAY[]::TEXT[]),
('NE', 'Niger', 'Africa', ARRAY[]::TEXT[]),
('NG', 'Nigeria', 'Africa', ARRAY[]::TEXT[]),
('NU', 'Niue', 'Oceania', ARRAY[]::TEXT[]),
('NF', 'Norfolk Island', 'Oceania', ARRAY[]::TEXT[]),
('KP', 'North Korea', 'Asia', ARRAY['Korea']),
('MK', 'North Macedonia', 'Europe', ARRAY['Macedonia']),
('MP', 'Northern Mariana Islands', 'Oceania', ARRAY[]::TEXT[]),
('NO', 'Norway', 'Europe', ARRAY[]::TEXT[]),
('OM', 'Oman', 'Asia', ARRAY[]::TEXT[]),
('PK', 'Pakistan', 'Asia', ARRAY[]::TEXT[]),
('PW', 'Palau', 'Oceania', ARRAY[]::TEXT[]),
('PS', 'Palestine', 'Asia', ARRAY['Palestinian Territories']),
('PA', 'Panama', 'North America', ARRAY[]::TEXT[]),
('PG', 'Papua New Guinea', 'Oceania', ARRAY[]::TEXT[]),
('PY', 'Paraguay', 'South America', ARRAY[]::TEXT[]),
('PE', 'Peru', 'South America', ARRAY[]::TEXT[]),
('PH', 'Philippines', 'Asia', ARRAY[]::TEXT[]),
('PN', 'Pitcairn Islands', 'Oceania', ARRAY[]::TEXT[]),
('PL', 'Poland', 'Europe', ARRAY[]::TEXT[]),
('PT', 'Portugal', 'Europe', ARRAY[]::TEXT[]),
('PR', 'Puerto Rico', 'North America', ARRAY[]::TEXT[]),
('QA', 'Qatar', 'Asia', ARRAY[]::TEXT[]),
('CG', 'Republic of the Congo', 'Africa', ARRAY['Congo', 'Congo-Brazzaville']),
('RE', 'Réunion', 'Africa', ARRAY[]::TEXT[]),
('RO', 'Romania', 'Europe', ARRAY[]::TEXT[]),
('RU', 'Russia', 'Europe', ARRAY['Russian Federation']),
('RW', 'Rwanda', 'Africa', ARRAY[]::TEXT[]),
('WS', 'Samoa', 'Oceania', ARRAY[]::TEXT[]),
('SM', 'San Marino', 'Europe', ARRAY[]::TEXT[]),
('ST', 'São Tomé & Príncipe', 'Africa', ARRAY[]::TEXT[]),
('SA', 'Saudi Arabia', 'Asia', ARRAY['KSA']),
('SN', 'Senegal', 'Africa', ARRAY[]::TEXT[]),
('RS', 'Serbia', 'Europe', ARRAY[]::TEXT[]),
('SC', 'Seychelles', 'Africa', ARRAY[]::TEXT[]),
('SL', 'Sierra Leone', 'Africa', ARRAY[]::TEXT[]),
('SG', 'Singapore', 'Asia', ARRAY[]::TEXT[]),
('SX', 'Sint Maarten', 'North America', ARRAY[]::TEXT[]),
('SK', 'Slovakia', 'Europe', ARRAY[]::TEXT[]),
('SI', 'Slovenia', 'Europe', ARRAY[]::TEXT[]),
('SB', 'Solomon Islands', 'Oceania', ARRAY[]::TEXT[]),
('SO', 'Somalia', 'Africa', ARRAY[]::TEXT[]),
('ZA', 'South Africa', 'Africa', ARRAY['SA']),
('GS', 'South Georgia & South Sandwich Islands', 'South America', ARRAY[]::TEXT[]),
('KR', 'South Korea', 'Asia', ARRAY['Korea']),
('SS', 'South Sudan', 'Africa', ARRAY[]::TEXT[]),
('ES', 'Spain', 'Europe', ARRAY[]::TEXT[]),
('LK', 'Sri Lanka', 'Asia', ARRAY[]::TEXT[]),
('BL', 'St. Barthélemy', 'North America', ARRAY[]::TEXT[]),
('SH', 'St. Helena', 'Africa', ARRAY[]::TEXT[]),
('KN', 'St. Kitts & Nevis', 'North America', ARRAY[]::TEXT[]),
('LC', 'St. Lucia', 'North America', ARRAY[]::TEXT[]),
('MF', 'St. Martin', 'North America', ARRAY[]::TEXT[]),
('PM', 'St. Pierre & Miquelon', 'North America', ARRAY[]::TEXT[]),
('VC', 'St. Vincent & Grenadines', 'North America', ARRAY[]::TEXT[]),
('SD', 'Sudan', 'Africa', ARRAY[]::TEXT[]),
('SR', 'Suriname', 'South America', ARRAY[]::TEXT[]),
('SJ', 'Svalbard & Jan Mayen', 'Europe', ARRAY[]::TEXT[]),
('SE', 'Sweden', 'Europe', ARRAY[]::TEXT[]),
('CH', 'Switzerland', 'Europe', ARRAY[]::TEXT[]),
('SY', 'Syria', 'Asia', ARRAY[]::TEXT[]),
('TW', 'Taiwan', 'Asia', ARRAY[]::TEXT[]),
('TJ', 'Tajikistan', 'Asia', ARRAY[]::TEXT[]),
('TZ', 'Tanzania', 'Africa', ARRAY['Tanzania']),
('TH', 'Thailand', 'Asia', ARRAY[]::TEXT[]),
('TL', 'Timor-Leste', 'Asia', ARRAY['East Timor']),
('TG', 'Togo', 'Africa', ARRAY[]::TEXT[]),
('TK', 'Tokelau', 'Oceania', ARRAY[]::TEXT[]),
('TO', 'Tonga', 'Oceania', ARRAY[]::TEXT[]),
('TT', 'Trinidad & Tobago', 'North America', ARRAY[]::TEXT[]),
('TN', 'Tunisia', 'Africa', ARRAY[]::TEXT[]),
('TR', 'Türkiye', 'Asia', ARRAY['Turkey']),
('TM', 'Turkmenistan', 'Asia', ARRAY[]::TEXT[]),
('TC', 'Turks & Caicos Islands', 'North America', ARRAY[]::TEXT[]),
('TV', 'Tuvalu', 'Oceania', ARRAY[]::TEXT[]),
('UM', 'U.S. Outlying Islands', 'Oceania', ARRAY[]::TEXT[]),
('VI', 'U.S. Virgin Islands', 'North America', ARRAY[]::TEXT[]),
('UG', 'Uganda', 'Africa', ARRAY[]::TEXT[]),
('UA', 'Ukraine', 'Europe', ARRAY[]::TEXT[]),
('AE', 'United Arab Emirates', 'Asia', ARRAY['UAE', 'Dubai', 'Abu Dhabi']),
('GB', 'United Kingdom', 'Europe', ARRAY['UK', 'Britain', 'England', 'Scotland', 'Wales', 'Northern Ireland']),
('US', 'United States', 'North America', ARRAY['USA', 'America', 'United States of America']),
('UY', 'Uruguay', 'South America', ARRAY[]::TEXT[]),
('UZ', 'Uzbekistan', 'Asia', ARRAY[]::TEXT[]),
('VU', 'Vanuatu', 'Oceania', ARRAY[]::TEXT[]),
('VA', 'Vatican City', 'Europe', ARRAY['Holy See']),
('VE', 'Venezuela', 'South America', ARRAY[]::TEXT[]),
('VN', 'Vietnam', 'Asia', ARRAY['Viet Nam']),
('WF', 'Wallis & Futuna', 'Oceania', ARRAY[]::TEXT[]),
('EH', 'Western Sahara', 'Africa', ARRAY[]::TEXT[]),
('YE', 'Yemen', 'Asia', ARRAY[]::TEXT[]),
('ZM', 'Zambia', 'Africa', ARRAY[]::TEXT[]),
('ZW', 'Zimbabwe', 'Africa', ARRAY[]::TEXT[]);
